2018-10-10 10:56:52.595 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 10:56:52.595 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 11:06:57.418 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 11:07:13.164 -03:00 [Debug] id de entrada: 1
2018-10-10 11:07:13.259 -03:00 [Error] An internal error occurred [LogId:ee041b34-892d-4a19-b7f2-7b737fbf092c].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 11:08:34.548 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 11:08:44.663 -03:00 [Debug] id de entrada: 1
2018-10-10 11:08:44.761 -03:00 [Error] An internal error occurred [LogId:e1ddd5af-0d30-479f-9b0d-13e445fca7a5].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 11:08:59.986 -03:00 [Debug] id de entrada: 2
2018-10-10 11:09:00.058 -03:00 [Information] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 11:09:03.706 -03:00 [Debug] id de entrada: 3
2018-10-10 11:09:03.777 -03:00 [Information] One or more core exceptions occurred while processing the request. Please check 'Items' for details.
WebApplication1.Teste.VsfException: One or more core exceptions occurred while processing the request. Please check 'Items' for details.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:02:46.607 -03:00 [Debug] Hosting starting
2018-10-10 12:02:46.704 -03:00 [Information] User profile is available. Using '"C:\Users\otc90893\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-10-10 12:02:46.707 -03:00 [Debug] Compatibility switch "AllowInputFormatterExceptionMessages" in type "MvcJsonOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.731 -03:00 [Debug] Compatibility switch "AllowCombiningAuthorizeFilters" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.731 -03:00 [Debug] Compatibility switch "AllowBindingHeaderValuesToNonStringModelTypes" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.731 -03:00 [Debug] Compatibility switch "AllowValidatingTopLevelNodes" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.731 -03:00 [Debug] Compatibility switch "InputFormatterExceptionPolicy" in type "MvcOptions" is using compatibility value MalformedInputExceptions for version Version_2_1
2018-10-10 12:02:46.731 -03:00 [Debug] Compatibility switch "SuppressBindingUndefinedValueToEnumType" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.738 -03:00 [Debug] Compatibility switch "AllowAreas" in type "RazorPagesOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.738 -03:00 [Debug] Compatibility switch "AllowMappingHeadRequestsToGetHandler" in type "RazorPagesOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.783 -03:00 [Debug] Compatibility switch "SuppressTempDataAttributePrefix" in type "MvcViewOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:46.823 -03:00 [Debug] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2018-10-10 12:02:46.856 -03:00 [Debug] Reading data from file '"C:\Users\otc90893\AppData\Local\ASP.NET\DataProtection-Keys\key-4191bbe8-d067-4fc3-9cf7-ef5ab334232a.xml"'.
2018-10-10 12:02:46.885 -03:00 [Debug] Reading data from file '"C:\Users\otc90893\AppData\Local\ASP.NET\DataProtection-Keys\key-8de43100-f78d-48d7-a536-a72fc3704f0c.xml"'.
2018-10-10 12:02:46.905 -03:00 [Debug] Reading data from file '"C:\Users\otc90893\AppData\Local\ASP.NET\DataProtection-Keys\key-ee116664-348d-4bb4-ada6-632516676ed5.xml"'.
2018-10-10 12:02:46.951 -03:00 [Debug] Found key {4191bbe8-d067-4fc3-9cf7-ef5ab334232a}.
2018-10-10 12:02:46.953 -03:00 [Debug] Found key {8de43100-f78d-48d7-a536-a72fc3704f0c}.
2018-10-10 12:02:46.953 -03:00 [Debug] Found key {ee116664-348d-4bb4-ada6-632516676ed5}.
2018-10-10 12:02:46.961 -03:00 [Debug] Considering key {ee116664-348d-4bb4-ada6-632516676ed5} with expiration date 2018-11-20 13:04:51Z as default key.
2018-10-10 12:02:47.015 -03:00 [Debug] Forwarded activator type request from "Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" to "Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60"
2018-10-10 12:02:47.016 -03:00 [Debug] Decrypting secret element using Windows DPAPI.
2018-10-10 12:02:47.017 -03:00 [Debug] Forwarded activator type request from "Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" to "Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60"
2018-10-10 12:02:47.018 -03:00 [Debug] Opening CNG algorithm '"AES"' from provider 'null' with chaining mode CBC.
2018-10-10 12:02:47.021 -03:00 [Debug] Opening CNG algorithm '"SHA256"' from provider 'null' with HMAC.
2018-10-10 12:02:47.025 -03:00 [Debug] Using key {ee116664-348d-4bb4-ada6-632516676ed5} as the default key.
2018-10-10 12:02:47.025 -03:00 [Debug] Key ring with default key {ee116664-348d-4bb4-ada6-632516676ed5} was loaded during application startup.
2018-10-10 12:02:47.444 -03:00 [Debug] An 'IServiceProvider' was created for internal use by Entity Framework.
2018-10-10 12:02:47.975 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.976 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.976 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.976 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.977 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.977 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.977 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.977 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.978 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.978 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.978 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.978 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.979 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.979 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.979 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.980 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.980 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.980 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.981 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.981 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.981 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.981 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.982 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.982 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.983 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.983 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.983 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.983 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.984 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.985 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.985 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.985 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:47.985 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.061 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.061 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.107 -03:00 [Debug] The index "{'UserId'}" was not created as the properties are already covered by the index "{'UserId', 'LoginProvider', 'Name'}".
2018-10-10 12:02:48.115 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.116 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.120 -03:00 [Debug] The index "{'UserId'}" was not created as the properties are already covered by the index "{'UserId', 'RoleId'}".
2018-10-10 12:02:48.133 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.135 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.159 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.159 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.160 -03:00 [Debug] The foreign key properties haven't been configured by convention because the best match "{'Id' : int}" are incompatible with the current principal key "{'Id' : Guid}". This message can be disregarded if explicit configuration has been specified.
2018-10-10 12:02:48.511 -03:00 [Information] Entity Framework Core "2.1.4-rtm-31024" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None"
2018-10-10 12:02:48.575 -03:00 [Debug] Migrating using database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:48.584 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.077 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.081 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.085 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.095 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.096 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.107 -03:00 [Debug] Executing DbCommand [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT OBJECT_ID(N'[__EFMigrationsHistory]');"
2018-10-10 12:02:53.249 -03:00 [Information] Executed DbCommand ("147"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT OBJECT_ID(N'[__EFMigrationsHistory]');"
2018-10-10 12:02:53.250 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.250 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.251 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.252 -03:00 [Debug] Executing DbCommand [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT OBJECT_ID(N'[__EFMigrationsHistory]');"
2018-10-10 12:02:53.268 -03:00 [Information] Executed DbCommand ("16"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT OBJECT_ID(N'[__EFMigrationsHistory]');"
2018-10-10 12:02:53.268 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.269 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.279 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.279 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.279 -03:00 [Debug] Executing DbCommand [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];"
2018-10-10 12:02:53.305 -03:00 [Information] Executed DbCommand ("26"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];"
2018-10-10 12:02:53.306 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.306 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.307 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:53.326 -03:00 [Information] No migrations were applied. The database is already up to date.
2018-10-10 12:02:53.329 -03:00 [Debug] '"ApplicationDbContext"' disposed.
2018-10-10 12:02:53.345 -03:00 [Information] Entity Framework Core "2.1.4-rtm-31024" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None"
2018-10-10 12:02:53.464 -03:00 [Debug] Compiling query model: "
"'"(from ApplicationRole r in DbSet<ApplicationRole>
where [r].NormalizedName == __normalizedName_0
select [r]).FirstOrDefault()"'
2018-10-10 12:02:53.526 -03:00 [Debug] Optimized query model: "
"'"(from ApplicationRole r in DbSet<ApplicationRole>
where [r].NormalizedName == __normalizedName_0
select [r]).FirstOrDefault()"'
2018-10-10 12:02:53.729 -03:00 [Debug] "(QueryContext queryContext) => IAsyncEnumerable<ApplicationRole> _InterceptExceptions(
    source: IAsyncEnumerable<ApplicationRole> _TrackEntities(
        results: IAsyncEnumerable<ApplicationRole> _ToSequence(() => Task<ApplicationRole> FirstOrDefault(
                source: IAsyncEnumerable<ApplicationRole> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
                        FROM [AspNetRoles] AS [r]
                        WHERE [r].[NormalizedName] = @__normalizedName_0, 
                    shaper: UnbufferedEntityShaper<ApplicationRole>), 
                cancellationToken: queryContext.CancellationToken)), 
        queryContext: queryContext, 
        entityTrackingInfos: { itemType: ApplicationRole }, 
        entityAccessors: List<Func<ApplicationRole, object>> 
        { 
            Func<ApplicationRole, ApplicationRole>, 
        }
    ), 
    contextType: Furiza.AspNetCore.Identity.EntityFrameworkCore.ApplicationDbContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)"
2018-10-10 12:02:53.905 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.905 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:53.978 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.054 -03:00 [Information] Executed DbCommand ("106"ms) [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.130 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.130 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.130 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.149 -03:00 [Debug] Context '"ApplicationRole"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.191 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.191 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.193 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.221 -03:00 [Information] Executed DbCommand ("29"ms) [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.222 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.222 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.222 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.222 -03:00 [Debug] Context '"ApplicationRole"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.229 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.229 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.229 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.252 -03:00 [Information] Executed DbCommand ("23"ms) [Parameters=["@__normalizedName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
FROM [AspNetRoles] AS [r]
WHERE [r].[NormalizedName] = @__normalizedName_0"
2018-10-10 12:02:54.252 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.252 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.253 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.253 -03:00 [Debug] Context '"ApplicationRole"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.261 -03:00 [Debug] Compiling query model: "
"'"(from ApplicationUser u in DbSet<ApplicationUser>
where [u].NormalizedUserName == __normalizedUserName_0
select [u]).FirstOrDefault()"'
2018-10-10 12:02:54.262 -03:00 [Debug] Optimized query model: "
"'"(from ApplicationUser u in DbSet<ApplicationUser>
where [u].NormalizedUserName == __normalizedUserName_0
select [u]).FirstOrDefault()"'
2018-10-10 12:02:54.271 -03:00 [Debug] "(QueryContext queryContext) => IAsyncEnumerable<ApplicationUser> _InterceptExceptions(
    source: IAsyncEnumerable<ApplicationUser> _TrackEntities(
        results: IAsyncEnumerable<ApplicationUser> _ToSequence(() => Task<ApplicationUser> FirstOrDefault(
                source: IAsyncEnumerable<ApplicationUser> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
                        FROM [AspNetUsers] AS [u]
                        WHERE [u].[NormalizedUserName] = @__normalizedUserName_0, 
                    shaper: UnbufferedEntityShaper<ApplicationUser>), 
                cancellationToken: queryContext.CancellationToken)), 
        queryContext: queryContext, 
        entityTrackingInfos: { itemType: ApplicationUser }, 
        entityAccessors: List<Func<ApplicationUser, object>> 
        { 
            Func<ApplicationUser, ApplicationUser>, 
        }
    ), 
    contextType: Furiza.AspNetCore.Identity.EntityFrameworkCore.ApplicationDbContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)"
2018-10-10 12:02:54.273 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.274 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.274 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.305 -03:00 [Information] Executed DbCommand ("32"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.331 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.331 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.331 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.331 -03:00 [Debug] Context '"ApplicationUser"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.357 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.357 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.358 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.387 -03:00 [Information] Executed DbCommand ("30"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.387 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.387 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.388 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.388 -03:00 [Debug] Context '"ApplicationUser"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.388 -03:00 [Debug] Opening connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.388 -03:00 [Debug] Opened connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.388 -03:00 [Debug] Executing DbCommand [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.410 -03:00 [Information] Executed DbCommand ("21"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
2018-10-10 12:02:54.410 -03:00 [Debug] A data reader was disposed.
2018-10-10 12:02:54.410 -03:00 [Debug] Closing connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.410 -03:00 [Debug] Closed connection to database '"FurizaWebApplication1"' on server '"(localdb)\mssqllocaldb"'.
2018-10-10 12:02:54.410 -03:00 [Debug] Context '"ApplicationUser"' started tracking '"ApplicationDbContext"' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2018-10-10 12:02:54.411 -03:00 [Debug] '"ApplicationDbContext"' disposed.
2018-10-10 12:02:54.437 -03:00 [Debug] Compatibility switch "AllowInputFormatterExceptionMessages" in type "MvcJsonOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "AllowCombiningAuthorizeFilters" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "AllowBindingHeaderValuesToNonStringModelTypes" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "AllowValidatingTopLevelNodes" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "InputFormatterExceptionPolicy" in type "MvcOptions" is using compatibility value MalformedInputExceptions for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "SuppressBindingUndefinedValueToEnumType" in type "MvcOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "AllowAreas" in type "RazorPagesOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.438 -03:00 [Debug] Compatibility switch "AllowMappingHeadRequestsToGetHandler" in type "RazorPagesOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.439 -03:00 [Debug] Compatibility switch "SuppressTempDataAttributePrefix" in type "MvcViewOptions" is using compatibility value True for version Version_2_1
2018-10-10 12:02:54.513 -03:00 [Debug] Failed to locate the development https certificate at 'null'.
2018-10-10 12:02:54.594 -03:00 [Debug] Using development certificate: "CN=localhost" (Thumbprint: "5F534C66F7449C180C9781B561573EE93F95A870")
2018-10-10 12:02:54.651 -03:00 [Debug] Hosting started
2018-10-10 12:02:54.651 -03:00 [Debug] Loaded hosting startup assembly "WebApplication1"
2018-10-10 12:02:55.162 -03:00 [Debug] Connection id ""0HLHEO5QL6NKO"" started.
2018-10-10 12:02:55.162 -03:00 [Debug] Connection id ""0HLHEO5QL6NKP"" started.
2018-10-10 12:02:55.384 -03:00 [Debug] Connection id ""0HLHEO5QL6NKP"" received FIN.
2018-10-10 12:02:55.384 -03:00 [Debug] Connection id ""0HLHEO5QL6NKO"" received FIN.
2018-10-10 12:02:55.385 -03:00 [Debug] Connection id ""0HLHEO5QL6NKO"" sending FIN.
2018-10-10 12:02:55.385 -03:00 [Debug] Connection id ""0HLHEO5QL6NKP"" sending FIN.
2018-10-10 12:02:55.438 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 12:02:55.438 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 12:02:55.454 -03:00 [Debug] Connection id ""0HLHEO5QL6NKP"" stopped.
2018-10-10 12:02:55.455 -03:00 [Debug] Connection id ""0HLHEO5QL6NKO"" stopped.
2018-10-10 12:02:56.792 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" started.
2018-10-10 12:02:56.845 -03:00 [Debug] Connection id ""0HLHEO5QL6NKR"" started.
2018-10-10 12:02:57.221 -03:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/swagger/index.html  
2018-10-10 12:02:57.247 -03:00 [Debug] Wildcard detected, all requests with hosts will be allowed.
2018-10-10 12:02:57.323 -03:00 [Debug] AuthenticationScheme: "Bearer" was not authenticated.
2018-10-10 12:02:57.354 -03:00 [Debug] Request successfully matched the route with name '"default"' and template '"{controller=Home}/{action=Index}/{id?}"'.
2018-10-10 12:02:57.362 -03:00 [Debug] No actions matched the current request. Route values: ["controller=swagger", "action=index.html"]
2018-10-10 12:02:57.362 -03:00 [Debug] No actions matched the current request. Route values: ["controller=swagger", "action=index.html"]
2018-10-10 12:02:57.363 -03:00 [Debug] Request did not match any routes.
2018-10-10 12:02:57.392 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" completed keep alive response.
2018-10-10 12:02:57.397 -03:00 [Information] Request finished in 185.471ms 200 text/html
2018-10-10 12:02:57.744 -03:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/swagger/v1/swagger.json  
2018-10-10 12:02:57.745 -03:00 [Debug] AuthenticationScheme: "Bearer" was not authenticated.
2018-10-10 12:02:57.745 -03:00 [Debug] Request successfully matched the route with name '"default"' and template '"{controller=Home}/{action=Index}/{id?}"'.
2018-10-10 12:02:57.745 -03:00 [Debug] No actions matched the current request. Route values: ["controller=swagger", "action=v1", "id=swagger.json"]
2018-10-10 12:02:57.745 -03:00 [Debug] No actions matched the current request. Route values: ["controller=swagger", "action=v1", "id=swagger.json"]
2018-10-10 12:02:57.745 -03:00 [Debug] Request did not match any routes.
2018-10-10 12:02:57.986 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" completed keep alive response.
2018-10-10 12:02:57.986 -03:00 [Information] Request finished in 242.7662ms 200 application/json;charset=utf-8
2018-10-10 12:03:08.547 -03:00 [Debug] Connection id ""0HLHEO5QL6NKR"" received FIN.
2018-10-10 12:03:08.547 -03:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/v1/Values/1  
2018-10-10 12:03:08.548 -03:00 [Debug] AuthenticationScheme: "Bearer" was not authenticated.
2018-10-10 12:03:08.549 -03:00 [Debug] Connection id ""0HLHEO5QL6NKR"" disconnecting.
2018-10-10 12:03:08.553 -03:00 [Debug] Connection id ""0HLHEO5QL6NKR"" sending FIN.
2018-10-10 12:03:08.570 -03:00 [Debug] Request successfully matched the route with name 'null' and template '"api/v{api-version:apiVersion}/Values/{id}"'.
2018-10-10 12:03:08.574 -03:00 [Debug] Connection id ""0HLHEO5QL6NKR"" stopped.
2018-10-10 12:03:08.586 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Put (WebApplication1)"' with id '"dd06d4a7-ff36-4f67-8518-8df302799740"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:08.586 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Delete (WebApplication1)"' with id '"b9f41ff1-478b-4c3c-9ef7-7619c01749a8"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:08.630 -03:00 [Information] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)"
2018-10-10 12:03:08.631 -03:00 [Debug] Execution plan of "authorization" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"]
2018-10-10 12:03:08.631 -03:00 [Debug] Execution plan of "resource" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter"]
2018-10-10 12:03:08.632 -03:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)"]
2018-10-10 12:03:08.632 -03:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2018-10-10 12:03:08.632 -03:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ProducesAttribute (Order: 0)"]
2018-10-10 12:03:08.656 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:08.658 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' using the name '"id"' in request data ...
2018-10-10 12:03:08.658 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:08.658 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:08.658 -03:00 [Debug] Attempting to validate the bound parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:08.667 -03:00 [Debug] Done attempting to validate the bound parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:08.745 -03:00 [Information] Executing action method "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" with arguments (["1"]) - Validation state: Valid
2018-10-10 12:03:08.932 -03:00 [Information] Executed action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" in 298.3237ms
2018-10-10 12:03:08.962 -03:00 [Error] An internal error occurred [LogId:d8c734e9-8288-4d1c-b275-f0ee46f134b0].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:03:08.976 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" completed keep alive response.
2018-10-10 12:03:08.976 -03:00 [Information] Request finished in 430.1619ms 500 application/json
2018-10-10 12:03:36.107 -03:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/v1/Values/1  
2018-10-10 12:03:36.107 -03:00 [Debug] AuthenticationScheme: "Bearer" was not authenticated.
2018-10-10 12:03:36.108 -03:00 [Debug] Request successfully matched the route with name 'null' and template '"api/v{api-version:apiVersion}/Values/{id}"'.
2018-10-10 12:03:36.108 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Put (WebApplication1)"' with id '"dd06d4a7-ff36-4f67-8518-8df302799740"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:36.108 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Delete (WebApplication1)"' with id '"b9f41ff1-478b-4c3c-9ef7-7619c01749a8"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:36.109 -03:00 [Information] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)"
2018-10-10 12:03:36.109 -03:00 [Debug] Execution plan of "authorization" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"]
2018-10-10 12:03:36.109 -03:00 [Debug] Execution plan of "resource" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter"]
2018-10-10 12:03:36.109 -03:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)"]
2018-10-10 12:03:36.109 -03:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2018-10-10 12:03:36.109 -03:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ProducesAttribute (Order: 0)"]
2018-10-10 12:03:36.110 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:36.110 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' using the name '"id"' in request data ...
2018-10-10 12:03:36.110 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:36.110 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:36.110 -03:00 [Debug] Attempting to validate the bound parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:36.110 -03:00 [Debug] Done attempting to validate the bound parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:36.149 -03:00 [Information] Executing action method "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" with arguments (["1"]) - Validation state: Valid
2018-10-10 12:03:36.200 -03:00 [Information] Executed action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" in 91.3883ms
2018-10-10 12:03:36.266 -03:00 [Error] An internal error occurred [LogId:04e5b15c-f91b-4135-bd5b-e0a19e761b01].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:03:36.266 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" completed keep alive response.
2018-10-10 12:03:36.266 -03:00 [Information] Request finished in 159.7002ms 500 application/json
2018-10-10 12:03:53.837 -03:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/v1/Values/2  
2018-10-10 12:03:53.837 -03:00 [Debug] AuthenticationScheme: "Bearer" was not authenticated.
2018-10-10 12:03:53.837 -03:00 [Debug] Request successfully matched the route with name 'null' and template '"api/v{api-version:apiVersion}/Values/{id}"'.
2018-10-10 12:03:53.837 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Put (WebApplication1)"' with id '"dd06d4a7-ff36-4f67-8518-8df302799740"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:53.837 -03:00 [Debug] Action '"WebApplication1.Controllers.ValuesController.Delete (WebApplication1)"' with id '"b9f41ff1-478b-4c3c-9ef7-7619c01749a8"' did not match the constraint '"Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint"'
2018-10-10 12:03:53.837 -03:00 [Information] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)"
2018-10-10 12:03:53.837 -03:00 [Debug] Execution plan of "authorization" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"]
2018-10-10 12:03:53.837 -03:00 [Debug] Execution plan of "resource" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter"]
2018-10-10 12:03:53.837 -03:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)"]
2018-10-10 12:03:53.837 -03:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2018-10-10 12:03:53.837 -03:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter", "Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ReportApiVersionsAttribute (Order: 0)", "Microsoft.AspNetCore.Mvc.ProducesAttribute (Order: 0)"]
2018-10-10 12:03:53.838 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:53.838 -03:00 [Debug] Attempting to bind parameter '"id"' of type '"System.Int32"' using the name '"id"' in request data ...
2018-10-10 12:03:53.838 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:53.838 -03:00 [Debug] Done attempting to bind parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:53.838 -03:00 [Debug] Attempting to validate the bound parameter '"id"' of type '"System.Int32"' ...
2018-10-10 12:03:53.838 -03:00 [Debug] Done attempting to validate the bound parameter '"id"' of type '"System.Int32"'.
2018-10-10 12:03:53.862 -03:00 [Information] Executing action method "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" with arguments (["2"]) - Validation state: Valid
2018-10-10 12:03:53.919 -03:00 [Information] Executed action "WebApplication1.Controllers.ValuesController.Get (WebApplication1)" in 81.694ms
2018-10-10 12:03:53.953 -03:00 [Information] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:03:53.958 -03:00 [Debug] Connection id ""0HLHEO5QL6NKQ"" completed keep alive response.
2018-10-10 12:03:53.958 -03:00 [Information] Request finished in 122.1796ms 400 application/json
2018-10-10 12:04:35.226 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 12:04:48.249 -03:00 [Error] An internal error occurred [LogId:2ad61276-4dde-40ee-8754-3060442e0421].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:05:04.104 -03:00 [Information] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 12:17:01.132 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 12:17:32.768 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 12:17:32.768 -03:00 [Debug] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
2018-10-10 13:01:26.154 -03:00 [Information] One or more errors occurred during model validation. Please check 'Items' for details.
Furiza.AspNetCore.ExceptionHandling.ModelValidationException: One or more errors occurred during model validation. Please check 'Items' for details.
   at Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute.OnActionExecuting(ActionExecutingContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ModelValidationAttribute.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 13:04:18.010 -03:00 [Error] An internal error occurred [LogId:1f8ef4af-7c84-46f6-8346-a93c21185fa2].
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Furiza.AspNetCore.Authentication.JwtBearer.UserTokenizer`1.GenerateToken(TUserData userData) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.Authentication.JwtBearer\UserTokenizer.cs:line 41
   at WebApplication1.Controllers.AuthController.PostAsync(AuthPost authPost) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\AuthController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 13:31:42.433 -03:00 [Error] An internal error occurred [LogId:c9f37f08-7e0d-4850-a1f0-10dfce72767f].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 45
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 14:49:54.122 -03:00 [Information] Applying migrations for Identity...
2018-10-10 14:50:06.756 -03:00 [Information] Migrations applied.
2018-10-10 14:50:06.757 -03:00 [Information] Filling database with system users and roles...
2018-10-10 14:50:09.609 -03:00 [Information] Database filled.
2018-10-10 15:16:12.130 -03:00 [Information] Applying migrations for Identity...
2018-10-10 15:16:24.492 -03:00 [Information] Migrations applied.
2018-10-10 15:16:24.494 -03:00 [Information] Filling database with system users and roles...
2018-10-10 15:16:26.784 -03:00 [Information] Database filled.
2018-10-10 15:27:33.535 -03:00 [Information] Applying migrations for Identity...
2018-10-10 15:27:45.947 -03:00 [Information] Migrations applied.
2018-10-10 15:27:45.948 -03:00 [Information] Filling database with system users and roles...
2018-10-10 15:27:48.257 -03:00 [Information] Database filled.
2018-10-10 15:32:03.250 -03:00 [Error] Failed executing DbCommand ("39"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[Company], [u].[ConcurrencyStamp], [u].[Department], [u].[Email], [u].[EmailConfirmed], [u].[FullName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0"
System.Threading.ThreadAbortException: System error.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.GetStateMachineBox[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
2018-10-10 15:32:03.398 -03:00 [Error] An exception occurred in the database while iterating the results of a query for context type '"Furiza.AspNetCore.Identity.EntityFrameworkCore.ApplicationDbContext"'."
""System.Threading.ThreadAbortException: System error.
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)"
System.Threading.ThreadAbortException: System error.
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
2018-10-10 15:32:03.422 -03:00 [Error] An exception occurred in the database while iterating the results of a query for context type '"Furiza.AspNetCore.Identity.EntityFrameworkCore.ApplicationDbContext"'."
""System.Threading.ThreadAbortException: System error.
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)"
System.Threading.ThreadAbortException: System error.
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
2018-10-10 15:32:52.869 -03:00 [Information] Applying migrations for Identity...
2018-10-10 15:32:54.167 -03:00 [Information] Migrations applied.
2018-10-10 15:32:54.167 -03:00 [Information] Filling database with system users and roles...
2018-10-10 15:32:54.846 -03:00 [Information] Database filled.
2018-10-10 16:07:04.304 -03:00 [Information] Applying migrations for Identity...
2018-10-10 16:07:07.201 -03:00 [Information] Migrations applied.
2018-10-10 16:07:07.202 -03:00 [Information] Filling database with system users and roles...
2018-10-10 16:07:07.881 -03:00 [Information] Database filled.
2018-10-10 16:45:27.231 -03:00 [Information] Applying migrations for Identity...
2018-10-10 16:45:28.739 -03:00 [Information] Migrations applied.
2018-10-10 16:45:28.739 -03:00 [Information] Filling database with system users and roles...
2018-10-10 16:45:29.471 -03:00 [Information] Database filled.
2018-10-10 16:55:11.282 -03:00 [Information] Applying migrations for Identity...
2018-10-10 16:55:12.706 -03:00 [Information] Migrations applied.
2018-10-10 16:55:12.707 -03:00 [Information] Filling database with system users and roles...
2018-10-10 16:55:13.398 -03:00 [Information] Database filled.
2018-10-10 17:05:23.652 -03:00 [Information] Applying migrations for Identity...
2018-10-10 17:05:24.992 -03:00 [Information] Migrations applied.
2018-10-10 17:05:24.994 -03:00 [Information] Filling database with system users and roles...
2018-10-10 17:05:25.654 -03:00 [Information] Database filled.
2018-10-10 17:07:26.256 -03:00 [Information] Applying migrations for Identity...
2018-10-10 17:07:27.860 -03:00 [Information] Migrations applied.
2018-10-10 17:07:27.862 -03:00 [Information] Filling database with system users and roles...
2018-10-10 17:07:28.536 -03:00 [Information] Database filled.
2018-10-10 17:19:13.501 -03:00 [Information] Applying migrations for Identity...
2018-10-10 17:19:15.152 -03:00 [Information] Migrations applied.
2018-10-10 17:19:15.153 -03:00 [Information] Filling database with system users and roles...
2018-10-10 17:19:15.845 -03:00 [Information] Database filled.
2018-10-10 18:31:06.528 -03:00 [Information] Applying migrations for Identity...
2018-10-10 18:31:09.039 -03:00 [Information] Migrations applied.
2018-10-10 18:31:09.040 -03:00 [Information] Filling database with system users and roles...
2018-10-10 18:31:09.754 -03:00 [Information] Database filled.
2018-10-10 18:34:14.322 -03:00 [Information] One or more errors occurred during model validation. Please check 'Items' for details.
Furiza.AspNetCore.ExceptionHandling.ModelValidationException: One or more errors occurred during model validation. Please check 'Items' for details.
   at Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute.OnActionExecuting(ActionExecutingContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ModelValidationAttribute.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 18:35:54.888 -03:00 [Information] One or more core exceptions occurred while processing the request. Please check 'Items' for details.
WebApplication1.Controllers.AuthException: One or more core exceptions occurred while processing the request. Please check 'Items' for details.
   at WebApplication1.Controllers.AuthController.PostAsync(AuthPost authPost) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\AuthController.cs:line 63
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 18:36:08.986 -03:00 [Information] One or more errors occurred during model validation. Please check 'Items' for details.
Furiza.AspNetCore.ExceptionHandling.ModelValidationException: One or more errors occurred during model validation. Please check 'Items' for details.
   at Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute.OnActionExecuting(ActionExecutingContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ModelValidationAttribute.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 18:36:21.616 -03:00 [Information] One or more core exceptions occurred while processing the request. Please check 'Items' for details.
WebApplication1.Controllers.AuthException: One or more core exceptions occurred while processing the request. Please check 'Items' for details.
   at WebApplication1.Controllers.AuthController.PostAsync(AuthPost authPost) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\AuthController.cs:line 63
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 18:36:33.821 -03:00 [Information] One or more errors occurred during model validation. Please check 'Items' for details.
Furiza.AspNetCore.ExceptionHandling.ModelValidationException: One or more errors occurred during model validation. Please check 'Items' for details.
   at Furiza.AspNetCore.ExceptionHandling.ModelValidationAttribute.OnActionExecuting(ActionExecutingContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ModelValidationAttribute.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:03:25.165 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:03:28.452 -03:00 [Information] Migrations applied.
2018-10-10 19:03:28.453 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:03:29.133 -03:00 [Information] Database filled.
2018-10-10 19:23:46.451 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:23:49.152 -03:00 [Information] Migrations applied.
2018-10-10 19:23:49.152 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:23:49.905 -03:00 [Information] Database filled.
2018-10-10 19:26:01.071 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:26:02.430 -03:00 [Information] Migrations applied.
2018-10-10 19:26:02.431 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:26:03.150 -03:00 [Information] Database filled.
2018-10-10 19:28:55.683 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:28:57.030 -03:00 [Information] Migrations applied.
2018-10-10 19:28:57.031 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:28:57.736 -03:00 [Information] Database filled.
2018-10-10 19:29:56.065 -03:00 [Error] An internal error occurred [LogId:647e8255-03eb-40ac-9668-2fcafedac8bd].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:32:37.256 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:32:38.645 -03:00 [Information] Migrations applied.
2018-10-10 19:32:38.646 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:32:39.367 -03:00 [Information] Database filled.
2018-10-10 19:32:49.428 -03:00 [Error] An internal error occurred [LogId:1817676e-0904-4458-a3be-eaacd466a954].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:32:56.292 -03:00 [Information] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 52
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:35:42.049 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:35:43.725 -03:00 [Information] Migrations applied.
2018-10-10 19:35:43.725 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:35:44.411 -03:00 [Information] Database filled.
2018-10-10 19:37:04.199 -03:00 [Error] An internal error occurred [LogId:ded634ad-2ecb-47dd-8009-19cb15f0caac].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:42:06.091 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:42:07.424 -03:00 [Information] Migrations applied.
2018-10-10 19:42:07.425 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:42:08.171 -03:00 [Information] Database filled.
2018-10-10 19:43:59.192 -03:00 [Error] An internal error occurred [LogId:d7d7b7c6-38fe-45d1-af1b-5c2d66d56880].
System.InvalidOperationException: ah vsf vai.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 50
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
2018-10-10 19:48:27.682 -03:00 [Information] Applying migrations for Identity...
2018-10-10 19:48:29.114 -03:00 [Information] Migrations applied.
2018-10-10 19:48:29.115 -03:00 [Information] Filling database with system users and roles...
2018-10-10 19:48:29.801 -03:00 [Information] Database filled.
2018-10-10 20:16:29.624 -03:00 [Information] Applying migrations for Identity...
2018-10-10 20:16:32.380 -03:00 [Information] Migrations applied.
2018-10-10 20:16:32.380 -03:00 [Information] Filling database with system users and roles...
2018-10-10 20:16:33.089 -03:00 [Information] Database filled.
2018-10-10 20:20:04.407 -03:00 [Information] Applying migrations for Identity...
2018-10-10 20:20:05.768 -03:00 [Information] Migrations applied.
2018-10-10 20:20:05.768 -03:00 [Information] Filling database with system users and roles...
2018-10-10 20:20:06.479 -03:00 [Information] Database filled.
2018-10-10 20:21:31.837 -03:00 [Information] O CPF fornecido está em branco, é inválido ou está em um formato inválido.
Furiza.Base.Core.Domain.BR.Exceptions.CpfInvalidoException: O CPF fornecido está em branco, é inválido ou está em um formato inválido.
   at WebApplication1.Controllers.ValuesController.Get(Int32 id) in C:\_ivanborges\github\furiza-aspnetcore\src\WebApplication1\Controllers\ValuesController.cs:line 52
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Furiza.AspNetCore.ExceptionHandling.ExceptionMiddleware.Invoke(HttpContext context) in C:\_ivanborges\github\furiza-aspnetcore\src\Furiza.AspNetCore.ExceptionHandling\ExceptionMiddleware.cs:line 28
